### ISSUE TITLE
Создавать рандомное секретное число вне цикла

### ISSUE THREAD

**Issue by pingvin1308** [denoolen/CleanCode.HomeWork#2]
https://github.com/denoolen/CleanCode.HomeWork/blob/55c50273014abf40e7c247d1f24a8db69628af8c/CleanCode.HomeWork.git/CleanCode.HomeWork.git/Program.cs#L7

Подсмотри как люди рандомили секретное число. Таким образом твоя программа будет действительно про угадывание случайного числа :)

**Comment by name-666** [comment]
Random rand = new Random();
 int secretrNumber = rand.Next(0,999);
https://docs.microsoft.com/ru-ru/dotnet/api/system.random?view=net-6.0
https://www.tutorialsteacher.com/articles/generate-random-numbers-in-csharp
